[package]
name = "bevy_ggrs_rapier_example"
version = "0.1.0"
edition = "2021"
license = "MIT"

[features]
default = []
debug = ["bevy-inspector-egui"]

[dependencies]
bevy-inspector-egui = { version = "0.10.0", optional = true }
bevy_asset_loader = "0.10.0"
bevy = "0.7.0"
bytemuck = {version="1.7.3", features= ["derive"]}
ggrs = { git = "https://github.com/gschup/ggrs", features=["sync-send"]}
bevy_ggrs = { git = "https://github.com/gschup/bevy_ggrs" }
matchbox_socket = { git = "https://github.com/johanhelsing/matchbox", features = ["ggrs-socket"] }
log = "0.4"
bevy_rapier2d = { git = "https://github.com/dimforge/bevy_rapier", features = [ "debug-render", "enhanced-determinism" ] }
bevy_ecs_ldtk = { version = "0.3.0" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
ggrs = { git = "https://github.com/gschup/ggrs", features=["sync-send", "wasm-bindgen"]}
bevy_ggrs = { git = "https://github.com/gschup/bevy_ggrs" , features=["wasm-bindgen"]}
bevy-web-resizer = "2.0.0"
web-sys = "0.3"


[patch.crates-io]
ggrs = { git = "https://github.com/gschup/ggrs" } # Force matchbox_socket to same version

